apiVersion: v1
appVersion: "1.6"
description: Deploys a cronJob which will renew ECR imagePullSecrets automatically
name: k8s-ecr-login-renew
version: "0.2"
maintainers:
- email: armen@stelth.io
  name: Armen "rmenr" Rostamian
keywords:
- aws
- ecr
- imagePullSecrets
sources:
- https://github.com/nabsul/k8s-ecr-login-renew
