apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "k8s-ecr-login-renew.namespace" . }}
  name: {{ include "k8s-ecr-login-renew.serviceAccount" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ include "k8s-ecr-login-renew.namespace" . }}
  name: {{ include "k8s-ecr-login-renew.role" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-ecr-login-renew.roleBinding" . }}
  namespace: {{ include "k8s-ecr-login-renew.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-ecr-login-renew.role" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-ecr-login-renew.serviceAccount" . }}
    namespace: {{ include "k8s-ecr-login-renew.namespace" . }}
